const { google } = require('googleapis');

function pad(value) {
  return String(value).padStart(2, '0');
}

function toCalendarDateTime(date) {
  return (
    date.getFullYear() +
    pad(date.getMonth() + 1) +
    pad(date.getDate()) +
    'T' +
    pad(date.getHours()) +
    pad(date.getMinutes()) +
    pad(date.getSeconds())
  );
}

function parseDurationHours(duration) {
  if (typeof duration === 'number') return duration;
  const match = String(duration || '').match(/(\d+(?:\.\d+)?)/);
  return match ? parseFloat(match[1]) : 1;
}

function buildStartDates() {
  const first = new Date();
  first.setDate(first.getDate() + 1);
  first.setHours(9, 0, 0, 0);
  return first;
}

function generateCalendarPayload(syllabus) {
  const modules = (syllabus && Array.isArray(syllabus.modules)) ? syllabus.modules : [];
  const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';

  let cursor = buildStartDates();
  const events = modules.map((moduleEntry, index) => {
    const title = moduleEntry.title || `Study Module ${index + 1}`;
    const hours = parseDurationHours(moduleEntry.duration);
    const start = new Date(cursor.getTime());
    const end = new Date(start.getTime() + hours * 60 * 60 * 1000);
    cursor = new Date(end.getTime());

    const topics = Array.isArray(moduleEntry.topics) ? moduleEntry.topics.join(', ') : '';
    const details = [
      `Module ${index + 1} of ${modules.length} - ${title}`,
      topics ? `Topics: ${topics}` : '',
      'Generated by ExamPrep Agent',
    ]
      .filter(Boolean)
      .join('\n');

    const url =
      'https://calendar.google.com/calendar/render?action=TEMPLATE' +
      `&text=${encodeURIComponent(`Study: ${title}`)}` +
      `&dates=${toCalendarDateTime(start)}/${toCalendarDateTime(end)}` +
      `&details=${encodeURIComponent(details)}` +
      `&ctz=${encodeURIComponent(timezone)}`;

    return {
      moduleIndex: index + 1,
      title,
      startISO: start.toISOString(),
      endISO: end.toISOString(),
      timezone,
      url,
      topics: Array.isArray(moduleEntry.topics) ? moduleEntry.topics : [],
    };
  });

  return { totalHours: syllabus.totalHours || null, modules: events };
}

module.exports = { generateCalendarPayload };